# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sn2hwLupM_dSQ0QStzZxj5uLnfjf19TX
"""

#!/usr/bin/env python
from distutils.core import setup
setup(
 name='Eureka',
 version='1.0',
 author='Johan Liu',
 license='MIT',
 long_description=open('README.md').read(),
)